# Generated by Django 3.1.1 on 2020-09-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0008_token_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPolicyDomains',
            fields=[
                ('token_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='domains', serialize=False, to='desecapi.tokenpolicy')),
                ('allow', models.ManyToManyField(blank=True, to='desecapi.Domain')),
            ],
        ),
    ]
