# Generated by Django 3.1.1 on 2020-09-15 21:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0009_token_policy_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenValidity',
            fields=[
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='validity', serialize=False, to='desecapi.token')),
                ('period', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('refresh', models.BooleanField(default=False, verbose_name='refresh on use')),
            ],
        ),
    ]
